version: "3"

services:
    my-web:
        container_name: my-web-name
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - my-mongo
        volumes:
            - .:/usr/src/app

    my-mongo:
        container_name: my-mongo-database
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: none
